### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by joshii-h** [paulgoio/searxng#25] opened 2022-02-07 08:40 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 100
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:123`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 0
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/qwant.py:110`
  * Function: `response`
  * Code: `search_results = loads(resp.text)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'api.qwant.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment] 2022-02-07 09:01
Duplicate of #24; Closing.

**Closed by mrpaulblack** 2022-02-07 09:01 UTC
