### ISSUE TITLE
Bug: library genesis engine

### ISSUE THREAD

**Issue by fleurc** [paulgoio/searxng#13] opened 2021-11-15 22:17 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ConnectError
  * Percentage: 50
  * Parameters: `(None, None, 'libgen.rs')`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment] 2021-11-16 22:13
Hi @fleurc ,
Thank you for your bug report. The issue is that the library of genesis engine sometimes does not return results... Tbh I cannot really do anything about it, there are just a lot of requests hitting my instance and because of all the requests my instance can get rate limited sometimes.

Is this happening a lot or only sometimes?

Also you can disable the engine in https://paulgo.io/preferences engine tab -> general ; if you dont really need the engine for example...

**Comment by fleurc** [comment] 2021-11-16 23:14
From what i tested it happens every 1-2 searches, It isn't consistent but it also happens a tad more often than i'd like. I normally don't need it, but having access to search with that engine is great for those corner cases i need.

I deactivated it in my preferences after seeing it isn't working consistently. Some other engines also aren't working but i use them even less so i just don't care if they don't work.

**Comment by mrpaulblack** [comment] 2021-11-16 23:23
So as a compromise: What would you think about moving the engine to a different category like the files or science category? This way it wont spam you with errors all the times and if you really need it you can just use the science or files category for example...

**Comment by fleurc** [comment] 2021-11-16 23:25
That would be great, i think i'll be doing that

**Comment by fleurc** [comment] 2021-11-16 23:28
If you feel inclined you can close this issue for me, since the actual problem wasn't solved i don't know if it should be closed.

**Comment by mrpaulblack** [comment] 2021-11-16 23:34
I am going to leave this open until the category change gets merged into this git repo, if thats ok...

**Comment by mrpaulblack** [comment] 2021-11-19 14:12
Moved Library of Genesis from general to files category in 20fe4bc2046a21d65e25f2784aba758c2620f661; Closing.

**Closed by mrpaulblack** 2021-11-19 14:12 UTC
