### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by felix-gouin** [paulgoio/searxng#55] opened 2023-09-12 00:44 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2023.9.11+f182abd6f

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 5
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment] 2023-09-12 06:41
Duplicate of https://github.com/paulgoio/searxng/issues/54

**Closed by mrpaulblack** 2023-09-12 06:41 UTC
