### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by XXDRD** [paulgoio/searxng#31] opened 2022-03-13 08:51 UTC
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2022.03.05-740e3bc9

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 40
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:123`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 0
  * Parameters: `('API error::q must be longer than or equal to 1 characters',)`
  * File name: `searx/engines/qwant.py:123`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'api.qwant.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment] 2022-03-13 08:54
Duplicate of #29; Closing. (The search still works, you can safely ignore the error message on a general search for now :D )

**Closed by mrpaulblack** 2022-03-13 08:54 UTC

**Comment by XXDRD** [comment] 2022-03-20 18:22
> Duplicate of #29; Closing. (The search still works, you can safely ignore the error message on a general search for now :D )
ok
